export interface MarkArg {
  flag: string;
  description: string;
  required: boolean;
  takesValue: boolean;
  repeatable?: boolean;
  placeholder?: string;
  choices?: string[];
  default?: string;
}

export interface Mark {
  id: string;
  name: string;
  category: string;
  description: string;
  script: string;
  runtime: "bash" | "bun";
  args: MarkArg[];
  example: string;
}

export const CATEGORIES = [
  "Git History",
  "Git Config",
  "Git Identity",
  "GitHub Platform",
  "Markdown / Docs",
  "Config / Dotfiles",
  "Enforcement",
  "Source Files",
  "License",
  "Supply Chain",
  "Container",
  "Well-Known",
  "Build",
  "Observability",
  "AI",
  "Invisible / Forensic",
  "Package",
] as const;

export const marks: Mark[] = [
  // --- Git History ---
  {
    id: "commit",
    name: "mark-commit",
    category: "Git History",
    description: "Structured commit with mark(<scope>): <msg> format, trailers, and optional annotated tag",
    script: "scripts/mark-commit",
    runtime: "bash",
    args: [
      { flag: "-m", description: "commit message", required: true, takesValue: true },
      { flag: "-s", description: "scope", required: true, takesValue: true },
      { flag: "--tag", description: "create annotated tag", required: false, takesValue: false },
      { flag: "--co-author", description: "name email", required: false, takesValue: true, placeholder: "Name email@example.com" },
      { flag: "--trailer", description: "key value", required: false, takesValue: true, repeatable: true, placeholder: "Task TRIV-42" },
    ],
    example: 'scripts/mark-commit -m "add auth" -s auth src/auth.ts',
  },
  {
    id: "note",
    name: "mark-note",
    category: "Git History",
    description: "Attach metadata to a commit via git notes without changing the SHA",
    script: "scripts/mark-note",
    runtime: "bash",
    args: [
      { flag: "-m", description: "note message", required: true, takesValue: true },
      { flag: "--commit", description: "commit ref", required: false, takesValue: true, default: "HEAD" },
      { flag: "--force", description: "overwrite existing note", required: false, takesValue: false },
    ],
    example: 'scripts/mark-note -m "reviewed by claude-code"',
  },
  {
    id: "branch",
    name: "mark-branch",
    category: "Git History",
    description: "Create a conventionally-named branch in prefix-<id>-<slug> format",
    script: "scripts/mark-branch",
    runtime: "bash",
    args: [
      { flag: "--prefix", description: "branch prefix", required: true, takesValue: true },
      { flag: "--id", description: "issue or task ID", required: true, takesValue: true },
      { flag: "--slug", description: "short description", required: true, takesValue: true },
      { flag: "--checkout", description: "switch to branch", required: false, takesValue: false },
    ],
    example: 'scripts/mark-branch --prefix feat --id 42 --slug "dark mode"',
  },
  // --- Git Config ---
  {
    id: "hook",
    name: "mark-hook",
    category: "Git Config",
    description: "Install pre-commit hook that stamps .git/mark-trail with agent identity",
    script: "scripts/mark-hook",
    runtime: "bash",
    args: [
      { flag: "--agent", description: "agent name", required: false, takesValue: true, default: "unknown-agent" },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "append to existing hook", required: false, takesValue: false },
    ],
    example: "scripts/mark-hook --agent claude-code",
  },
  {
    id: "gitattributes",
    name: "mark-gitattributes",
    category: "Git Config",
    description: "Drop .gitattributes with LF normalization and diff driver settings",
    script: "scripts/mark-gitattributes",
    runtime: "bash",
    args: [
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: "scripts/mark-gitattributes",
  },
  {
    id: "blame-ignore",
    name: "mark-blame-ignore",
    category: "Git Config",
    description: "Track commit SHAs in .git-blame-ignore-revs and optionally configure git blame.ignoreRevsFile",
    script: "scripts/mark-blame-ignore",
    runtime: "bash",
    args: [
      { flag: "--commit", description: "commit SHA or ref", required: true, takesValue: true },
      { flag: "--file", description: "target file", required: false, takesValue: true, default: ".git-blame-ignore-revs" },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--configure", description: "set git config blame.ignoreRevsFile", required: false, takesValue: false },
      { flag: "--allow-outside-repo", description: "allow writing outside repo root", required: false, takesValue: false },
    ],
    example: "scripts/mark-blame-ignore --commit HEAD --configure",
  },
  // --- Git Identity ---
  {
    id: "mailmap",
    name: "mark-mailmap",
    category: "Git Identity",
    description: "Add .mailmap entry for author name/email canonicalization",
    script: "scripts/mark-mailmap",
    runtime: "bash",
    args: [
      { flag: "--name", description: "canonical name", required: true, takesValue: true },
      { flag: "--email", description: "canonical email", required: true, takesValue: true },
      { flag: "--old-name", description: "old name to map from", required: false, takesValue: true },
      { flag: "--old-email", description: "old email to map from", required: false, takesValue: true },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
    ],
    example: 'scripts/mark-mailmap --name "Milian" --email "m@example.com" --old-email "old@example.com"',
  },
  {
    id: "signoff",
    name: "mark-signoff",
    category: "Git Identity",
    description: "Add Signed-off-by trailer (Developer Certificate of Origin)",
    script: "scripts/mark-signoff",
    runtime: "bash",
    args: [
      { flag: "--name", description: "signer name", required: false, takesValue: true },
      { flag: "--email", description: "signer email", required: false, takesValue: true },
      { flag: "--commit", description: "commit ref to check", required: false, takesValue: true },
    ],
    example: "scripts/mark-signoff",
  },
  {
    id: "sign",
    name: "mark-sign",
    category: "Git Identity",
    description: "GPG/SSH sign a commit or tag",
    script: "scripts/mark-sign",
    runtime: "bash",
    args: [
      { flag: "--commit", description: "commit ref", required: false, takesValue: true },
      { flag: "--tag", description: "tag name to sign", required: false, takesValue: true },
      { flag: "--key-type", description: "gpg | ssh", required: false, takesValue: true, default: "gpg", choices: ["gpg", "ssh"] },
    ],
    example: "scripts/mark-sign --tag v1.0.0",
  },
  // --- GitHub Platform ---
  {
    id: "pr",
    name: "mark-pr",
    category: "GitHub Platform",
    description: "Create a pull request via gh pr create",
    script: "scripts/mark-pr",
    runtime: "bash",
    args: [
      { flag: "--title", description: "PR title", required: true, takesValue: true },
      { flag: "--body", description: "PR description", required: false, takesValue: true },
      { flag: "--base", description: "base branch", required: false, takesValue: true, default: "main" },
      { flag: "--draft", description: "create as draft", required: false, takesValue: false },
    ],
    example: 'scripts/mark-pr --title "feat: add dark mode" --base main',
  },
  {
    id: "issue",
    name: "mark-issue",
    category: "GitHub Platform",
    description: "Create a GitHub issue via gh issue create with labels",
    script: "scripts/mark-issue",
    runtime: "bash",
    args: [
      { flag: "--title", description: "issue title", required: true, takesValue: true },
      { flag: "--body", description: "issue body", required: false, takesValue: true },
      { flag: "--label", description: "label (repeatable)", required: false, takesValue: true, repeatable: true, placeholder: "bug,ui" },
    ],
    example: 'scripts/mark-issue --title "Bug: login fails" --label bug',
  },
  {
    id: "release",
    name: "mark-release",
    category: "GitHub Platform",
    description: "Create a GitHub release via gh release create",
    script: "scripts/mark-release",
    runtime: "bash",
    args: [
      { flag: "--tag", description: "version tag", required: true, takesValue: true },
      { flag: "--title", description: "release title", required: false, takesValue: true },
      { flag: "--notes", description: "release notes", required: false, takesValue: true },
      { flag: "--draft", description: "create as draft", required: false, takesValue: false },
    ],
    example: 'scripts/mark-release --tag v1.0.0 --title "Initial release"',
  },
  {
    id: "topic",
    name: "mark-topic",
    category: "GitHub Platform",
    description: "Set repository topics via gh api",
    script: "scripts/mark-topic",
    runtime: "bash",
    args: [
      { flag: "--topics", description: "comma-separated topics", required: true, takesValue: true },
      { flag: "--repo", description: "owner/repo", required: false, takesValue: true },
    ],
    example: 'scripts/mark-topic --topics "ai,automation,devtools"',
  },
  // --- Markdown / Docs ---
  {
    id: "badge",
    name: "mark-badge",
    category: "Markdown / Docs",
    description: "Inject a shields.io badge or attribution line into README.md",
    script: "scripts/mark-badge",
    runtime: "bash",
    args: [
      { flag: "--label", description: "badge label", required: true, takesValue: true },
      { flag: "--message", description: "badge message", required: true, takesValue: true },
      { flag: "--color", description: "badge color", required: false, takesValue: true, default: "blue" },
      { flag: "--url", description: "link URL", required: false, takesValue: true },
      { flag: "--file", description: "target file", required: false, takesValue: true, default: "README.md" },
    ],
    example: 'scripts/mark-badge --label "Built by" --message "Claude" --color blue',
  },
  {
    id: "changelog",
    name: "mark-changelog",
    category: "Markdown / Docs",
    description: "Prepend a structured entry to CHANGELOG.md",
    script: "scripts/mark-changelog",
    runtime: "bash",
    args: [
      { flag: "--version", description: "version string", required: true, takesValue: true },
      { flag: "--message", description: "change description", required: true, takesValue: true },
      { flag: "--file", description: "target file", required: false, takesValue: true, default: "CHANGELOG.md" },
    ],
    example: 'scripts/mark-changelog --version 1.2.0 --message "Add badge injection"',
  },
  {
    id: "citation",
    name: "mark-citation",
    category: "Markdown / Docs",
    description: "Drop CITATION.cff with title, version, and authors for software citation",
    script: "scripts/mark-citation",
    runtime: "bash",
    args: [
      { flag: "--title", description: "software title", required: true, takesValue: true },
      { flag: "--author", description: "author name (repeatable)", required: true, takesValue: true, repeatable: true, placeholder: "Jane Doe,John Doe" },
      { flag: "--version", description: "release version", required: false, takesValue: true, default: "0.1.0" },
      { flag: "--date", description: "release date (YYYY-MM-DD)", required: false, takesValue: true },
      { flag: "--message", description: "citation message text", required: false, takesValue: true, default: "If you use this software, please cite it." },
      { flag: "--doi", description: "DOI string", required: false, takesValue: true },
      { flag: "--url", description: "repository URL", required: false, takesValue: true },
      { flag: "--set", description: "extra key=value field (repeatable)", required: false, takesValue: true, repeatable: true, placeholder: "license=MIT" },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing file", required: false, takesValue: false },
    ],
    example: 'scripts/mark-citation --title "make-a-mark" --author "Milian0402"',
  },
  {
    id: "scaffold",
    name: "mark-scaffold",
    category: "Markdown / Docs",
    description: "Drop standard project files: CONTRIBUTING, SECURITY, CODE_OF_CONDUCT, CODEOWNERS, FUNDING, templates",
    script: "scripts/mark-scaffold",
    runtime: "bash",
    args: [
      { flag: "--type", description: "contributing | security | code-of-conduct | codeowners | funding | issue-template | pr-template", required: true, takesValue: true, choices: ["contributing", "security", "code-of-conduct", "codeowners", "funding", "issue-template", "pr-template"] },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: "scripts/mark-scaffold --type contributing",
  },
  {
    id: "adr",
    name: "mark-adr",
    category: "Markdown / Docs",
    description: "Create a numbered Architecture Decision Record in docs/adr/",
    script: "scripts/mark-adr",
    runtime: "bash",
    args: [
      { flag: "--title", description: "ADR title", required: true, takesValue: true },
      { flag: "--dir", description: "output directory", required: false, takesValue: true, default: "docs/adr" },
      { flag: "--status", description: "status", required: false, takesValue: true, default: "Accepted", choices: ["Proposed", "Accepted", "Deprecated", "Superseded"] },
    ],
    example: 'scripts/mark-adr --title "Use Bun as runtime"',
  },
  // --- Config / Dotfiles ---
  {
    id: "config",
    name: "mark-config",
    category: "Config / Dotfiles",
    description: "Drop a marker YAML config file (.<tool>.yml) declaring tool usage",
    script: "scripts/mark-config",
    runtime: "bash",
    args: [
      { flag: "--tool", description: "tool name", required: true, takesValue: true },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: "scripts/mark-config --tool triverge",
  },
  {
    id: "editorconfig",
    name: "mark-editorconfig",
    category: "Config / Dotfiles",
    description: "Drop .editorconfig with sensible defaults",
    script: "scripts/mark-editorconfig",
    runtime: "bash",
    args: [
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: "scripts/mark-editorconfig",
  },
  {
    id: "gitignore",
    name: "mark-gitignore",
    category: "Config / Dotfiles",
    description: "Manage an idempotent preset block in .gitignore",
    script: "scripts/mark-gitignore",
    runtime: "bash",
    args: [
      { flag: "--preset", description: "general | node | python", required: false, takesValue: true, default: "general", choices: ["general", "node", "python"] },
      { flag: "--pattern", description: "extra ignore pattern (repeatable)", required: false, takesValue: true, repeatable: true, placeholder: ".cache/,*.tmp" },
      { flag: "--block", description: "custom managed block name", required: false, takesValue: true, placeholder: "build-artifacts" },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--allow-symlink", description: "allow writing through symlinked .gitignore", required: false, takesValue: false },
    ],
    example: "scripts/mark-gitignore --preset node",
  },
  {
    id: "nodeversion",
    name: "mark-nodeversion",
    category: "Config / Dotfiles",
    description: "Drop .nvmrc or .node-version with a specified Node.js version",
    script: "scripts/mark-nodeversion",
    runtime: "bash",
    args: [
      { flag: "--version", description: "Node.js version", required: true, takesValue: true },
      { flag: "--format", description: "nvmrc | node-version", required: false, takesValue: true, default: "nvmrc", choices: ["nvmrc", "node-version"] },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: "scripts/mark-nodeversion --version 22.0.0",
  },
  {
    id: "dependabot",
    name: "mark-dependabot",
    category: "Config / Dotfiles",
    description: "Drop .github/dependabot.yml with weekly update schedule",
    script: "scripts/mark-dependabot",
    runtime: "bash",
    args: [
      { flag: "--ecosystem", description: "package ecosystem", required: false, takesValue: true, default: "npm", choices: ["npm", "pip", "cargo", "gomod", "docker"] },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: "scripts/mark-dependabot --ecosystem npm",
  },
  {
    id: "workflow",
    name: "mark-workflow",
    category: "Config / Dotfiles",
    description: "Drop a GitHub Actions workflow into .github/workflows/",
    script: "scripts/mark-workflow",
    runtime: "bash",
    args: [
      { flag: "--name", description: "workflow name", required: true, takesValue: true },
      { flag: "--trigger", description: "push | pr | schedule", required: false, takesValue: true, default: "push", choices: ["push", "pr", "schedule"] },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: 'scripts/mark-workflow --name "CI" --trigger push',
  },
  // --- Enforcement ---
  {
    id: "commitlint",
    name: "mark-commitlint",
    category: "Enforcement",
    description: "Drop commitlint config + husky commit-msg hook for conventional commits",
    script: "scripts/mark-commitlint",
    runtime: "bash",
    args: [
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: "scripts/mark-commitlint",
  },
  {
    id: "lint-staged",
    name: "mark-lint-staged",
    category: "Enforcement",
    description: "Drop lint-staged config + husky pre-commit hook",
    script: "scripts/mark-lint-staged",
    runtime: "bash",
    args: [
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: "scripts/mark-lint-staged",
  },
  // --- Source Files ---
  {
    id: "header",
    name: "mark-header",
    category: "Source Files",
    description: "Prepend copyright/license banner with @generated marker",
    script: "scripts/mark-header.ts",
    runtime: "bun",
    args: [
      { flag: "--author", description: "copyright holder", required: false, takesValue: true, default: "Unknown" },
      { flag: "--license", description: "SPDX identifier", required: false, takesValue: true, default: "MIT" },
      { flag: "--year", description: "copyright year", required: false, takesValue: true },
      { flag: "--url", description: "repository URL", required: false, takesValue: true },
    ],
    example: 'bun scripts/mark-header.ts --author "Milian0402" src/index.ts',
  },
  {
    id: "watermark",
    name: "mark-watermark",
    category: "Source Files",
    description: "Inject build-hash watermark (date + git SHA + author)",
    script: "scripts/mark-watermark.ts",
    runtime: "bun",
    args: [
      { flag: "--author", description: "author name", required: false, takesValue: true, default: "unknown" },
      { flag: "--placement", description: "top | bottom | after-imports", required: false, takesValue: true, default: "top", choices: ["top", "bottom", "after-imports"] },
    ],
    example: "bun scripts/mark-watermark.ts --author claude-code src/index.ts",
  },
  {
    id: "annotate",
    name: "mark-annotate",
    category: "Source Files",
    description: "Inject @generated, @todo, @fixme, or @marked-by comment",
    script: "scripts/mark-annotate.ts",
    runtime: "bun",
    args: [
      { flag: "--type", description: "@generated | @todo | @fixme | @marked-by", required: true, takesValue: true, choices: ["@generated", "@todo", "@fixme", "@marked-by"] },
      { flag: "--message", description: "annotation message", required: false, takesValue: true },
      { flag: "--author", description: "author for @marked-by", required: false, takesValue: true },
      { flag: "--line", description: "insert before line number", required: false, takesValue: true },
    ],
    example: "bun scripts/mark-annotate.ts --type @generated src/generated.ts",
  },
  {
    id: "docstring",
    name: "mark-docstring",
    category: "Source Files",
    description: "Add JSDoc or Python docstring to a named function",
    script: "scripts/mark-docstring.ts",
    runtime: "bun",
    args: [
      { flag: "--fn", description: "function name", required: true, takesValue: true },
      { flag: "--description", description: "short description", required: false, takesValue: true },
      { flag: "--param", description: "param description (repeatable)", required: false, takesValue: true, repeatable: true, placeholder: "userId - unique user id" },
      { flag: "--returns", description: "return description", required: false, takesValue: true },
    ],
    example: 'bun scripts/mark-docstring.ts --fn login --description "Authenticates user" src/auth.ts',
  },
  // --- License ---
  {
    id: "spdx",
    name: "mark-spdx",
    category: "License",
    description: "Prepend SPDX-License-Identifier + SPDX-FileCopyrightText headers (REUSE standard)",
    script: "scripts/mark-spdx.ts",
    runtime: "bun",
    args: [
      { flag: "--license", description: "SPDX license expression", required: false, takesValue: true, default: "MIT" },
      { flag: "--copyright", description: "copyright holder", required: false, takesValue: true, default: "Unknown" },
      { flag: "--year", description: "copyright year", required: false, takesValue: true },
    ],
    example: 'bun scripts/mark-spdx.ts --license MIT --copyright "Milian0402" src/index.ts',
  },
  // --- Supply Chain ---
  {
    id: "sbom",
    name: "mark-sbom",
    category: "Supply Chain",
    description: "Generate SPDX or CycloneDX Software Bill of Materials stub",
    script: "scripts/mark-sbom",
    runtime: "bash",
    args: [
      { flag: "--format", description: "spdx | cyclonedx", required: false, takesValue: true, default: "spdx", choices: ["spdx", "cyclonedx"] },
      { flag: "--output", description: "output file", required: false, takesValue: true },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: "scripts/mark-sbom --format spdx",
  },
  {
    id: "attestation",
    name: "mark-attestation",
    category: "Supply Chain",
    description: "Create SLSA provenance attestation (in-toto Statement v1)",
    script: "scripts/mark-attestation",
    runtime: "bash",
    args: [
      { flag: "--subject", description: "artifact file", required: true, takesValue: true },
      { flag: "--type", description: "predicate type URL", required: false, takesValue: true },
      { flag: "--output", description: "output file", required: false, takesValue: true },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: "scripts/mark-attestation --subject dist/app.js",
  },
  // --- Container ---
  {
    id: "dockerfile",
    name: "mark-dockerfile",
    category: "Container",
    description: "Drop Dockerfile with OCI standard labels (org.opencontainers.image.*)",
    script: "scripts/mark-dockerfile",
    runtime: "bash",
    args: [
      { flag: "--base", description: "base image", required: false, takesValue: true, default: "node:22-alpine" },
      { flag: "--name", description: "app name", required: false, takesValue: true },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: "scripts/mark-dockerfile --base node:22-alpine --name myapp",
  },
  {
    id: "oci-labels",
    name: "mark-oci-labels",
    category: "Container",
    description: "Add/update OCI annotations in an existing Dockerfile",
    script: "scripts/mark-oci-labels.ts",
    runtime: "bun",
    args: [
      { flag: "--title", description: "image title", required: false, takesValue: true },
      { flag: "--version", description: "image version", required: false, takesValue: true },
      { flag: "--source", description: "source code URL", required: false, takesValue: true },
      { flag: "--authors", description: "image authors", required: false, takesValue: true },
      { flag: "--set", description: "custom key=value (repeatable)", required: false, takesValue: true, repeatable: true, placeholder: "com.example.env=prod" },
    ],
    example: 'bun scripts/mark-oci-labels.ts --title "myapp" --version "1.0" Dockerfile',
  },
  // --- Well-Known ---
  {
    id: "humans",
    name: "mark-humans",
    category: "Well-Known",
    description: "Drop humans.txt (credits file for people behind the site)",
    script: "scripts/mark-humans",
    runtime: "bash",
    args: [
      { flag: "--name", description: "person name", required: true, takesValue: true },
      { flag: "--role", description: "role title", required: false, takesValue: true, default: "Developer" },
      { flag: "--twitter", description: "twitter handle", required: false, takesValue: true },
      { flag: "--site", description: "website URL", required: false, takesValue: true },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: 'scripts/mark-humans --name "Milian" --role "Creator"',
  },
  {
    id: "security",
    name: "mark-security",
    category: "Well-Known",
    description: "Drop .well-known/security.txt (RFC 9116 vulnerability disclosure)",
    script: "scripts/mark-security",
    runtime: "bash",
    args: [
      { flag: "--contact", description: "contact URL or email", required: true, takesValue: true },
      { flag: "--expires", description: "expiry date (default: +1 year)", required: false, takesValue: true },
      { flag: "--policy", description: "security policy URL", required: false, takesValue: true },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: 'scripts/mark-security --contact "mailto:security@example.com"',
  },
  {
    id: "robots",
    name: "mark-robots",
    category: "Well-Known",
    description: "Drop robots.txt with crawling rules",
    script: "scripts/mark-robots",
    runtime: "bash",
    args: [
      { flag: "--sitemap", description: "sitemap URL", required: false, takesValue: true },
      { flag: "--disallow", description: "disallowed path", required: false, takesValue: true },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: "scripts/mark-robots --sitemap https://example.com/sitemap.xml",
  },
  // --- Build ---
  {
    id: "sourcemap",
    name: "mark-sourcemap",
    category: "Build",
    description: "Inject //# sourceMappingURL comment into JS/CSS files",
    script: "scripts/mark-sourcemap.ts",
    runtime: "bun",
    args: [
      { flag: "--url", description: "source map URL", required: false, takesValue: true },
      { flag: "--remove", description: "remove existing sourceMappingURL", required: false, takesValue: false },
    ],
    example: "bun scripts/mark-sourcemap.ts --url app.js.map dist/app.js",
  },
  // --- Observability ---
  {
    id: "otel",
    name: "mark-otel",
    category: "Observability",
    description: "Drop OpenTelemetry resource config with service attributes",
    script: "scripts/mark-otel",
    runtime: "bash",
    args: [
      { flag: "--service", description: "service name", required: true, takesValue: true },
      { flag: "--version", description: "service version", required: false, takesValue: true, default: "0.1.0" },
      { flag: "--env", description: "deployment environment", required: false, takesValue: true, default: "development" },
      { flag: "--repo", description: "repo path", required: false, takesValue: true, default: "." },
      { flag: "--force", description: "overwrite existing", required: false, takesValue: false },
    ],
    example: 'scripts/mark-otel --service "my-api" --env production',
  },
  // --- AI ---
  {
    id: "ai-disclosure",
    name: "mark-ai-disclosure",
    category: "AI",
    description: "Add @ai-generated disclosure comment with model, date, and scope",
    script: "scripts/mark-ai-disclosure",
    runtime: "bash",
    args: [
      { flag: "--model", description: "AI model name", required: true, takesValue: true },
      { flag: "--date", description: "generation date", required: false, takesValue: true },
      { flag: "--scope", description: "full | partial", required: false, takesValue: true, default: "partial", choices: ["full", "partial"] },
    ],
    example: 'scripts/mark-ai-disclosure --model "claude-opus-4" --scope partial src/auth.ts',
  },
  // --- Invisible / Forensic ---
  {
    id: "gitkeep",
    name: "mark-gitkeep",
    category: "Invisible / Forensic",
    description: "Create .gitkeep in empty directories to track them in git",
    script: "scripts/mark-gitkeep",
    runtime: "bash",
    args: [],
    example: "scripts/mark-gitkeep src/assets src/generated",
  },
  // --- Package ---
  {
    id: "metadata",
    name: "mark-metadata",
    category: "Package",
    description: "Edit package.json fields: set values, add/remove keywords",
    script: "scripts/mark-metadata.ts",
    runtime: "bun",
    args: [
      { flag: "--set", description: "key=value (repeatable)", required: false, takesValue: true, repeatable: true, placeholder: "author=Milian0402" },
      { flag: "--add-keyword", description: "keyword to add (repeatable)", required: false, takesValue: true, repeatable: true, placeholder: "devtools,automation" },
      { flag: "--remove-keyword", description: "keyword to remove (repeatable)", required: false, takesValue: true, repeatable: true, placeholder: "deprecated" },
    ],
    example: 'bun scripts/mark-metadata.ts --set author="Milian0402" --add-keyword devtools',
  },
];

export const markById = Object.fromEntries(marks.map((m) => [m.id, m]));
export const marksByCategory = marks.reduce<Record<string, Mark[]>>((acc, m) => {
  (acc[m.category] ??= []).push(m);
  return acc;
}, {});
